---

- name: Install Python packages
  package:
	name={{item}}
	state=latest
  with_items:
	- "{{python_mysqld}}"
	- python-pip
	- python-boto
	- python-pycurl
	- "{{python_dev}}"
	- python-lxml
	- python-yaml

- name: Install Python libraries
  pip: name={{item}}
  with_items:
	- mwclient
