---

- name: Install misc packages
  package:
	name={{item}}
	state=latest
  with_items:
	- unzip
	- curl
	- tree
	- "{{libxml2_dev}}"
	- "{{libxslt_dev}}"
	- git
	- duplicity
	- graphviz
	- uuid
	- "{{imagemagick}}"
	- "{{lua}}"
	- vim
	- python-boto
	- memcached
	- "{{libyaml_dev}}"
	- "{{selinux_python}}"
