---

- name: Install Apache packages
  package: name={{item}}
	state=latest
  with_items:
	- "{{apache}}"
	- "{{mod_auth_mysql}}"

- name: Activate mod rewrite
  apache2_module: state=present name=rewrite
  notify: Start Apache2
