- include: Debian-version.yml
  name: php 7
  when: php_version == 7
  vars:
    php_ver: ""
    phpinidir: /etc/php.d
    php_memcache: php-memcache
    php_sqlite: php-sqlite3

- include: Debian-version.yml
  name: php 5
  when: php_version == 5
  vars:
    php_ver: 5
    phpinidir: /etc/php.d
    php_memcache: php{{php_ver}}-memcache
    php_sqlite: php5-sqlite

